// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PriceTrend.Data;

#nullable disable

namespace PriceTrend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260915133546_AddUsersTable")]
    partial class AddUsersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PriceTrend.Models.Product.Category", b =>
                {
                    b.Property<Guid>("CategoryGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryGuid");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("PriceTrend.Models.Product.Item", b =>
                {
                    b.Property<Guid>("ItemGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CategoryGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryGuid1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("HighestPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("HistoricalLowestPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("LowestPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MainImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ItemGuid");

                    b.HasIndex("CategoryGuid1");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("PriceTrend.Models.Product.Platform", b =>
                {
                    b.Property<Guid>("PlatformGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BaseUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlatformName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("PlatformGuid");

                    b.ToTable("Platforms");
                });

            modelBuilder.Entity("PriceTrend.Models.Product.PlatformItem", b =>
                {
                    b.Property<Guid>("PlatformItemGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ItemGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ItemUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastScrapedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OuterItemId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PlatformGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PlatformItemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("StockStatus")
                        .HasColumnType("tinyint");

                    b.HasKey("PlatformItemGuid");

                    b.HasIndex("ItemGuid");

                    b.HasIndex("PlatformGuid");

                    b.ToTable("PlatformItems");
                });

            modelBuilder.Entity("PriceTrend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PriceTrend.Models.Product.Item", b =>
                {
                    b.HasOne("PriceTrend.Models.Product.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryGuid1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PriceTrend.Models.Product.PlatformItem", b =>
                {
                    b.HasOne("PriceTrend.Models.Product.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PriceTrend.Models.Product.Platform", "Platform")
                        .WithMany("PlatformItems")
                        .HasForeignKey("PlatformGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("PriceTrend.Models.Product.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("PriceTrend.Models.Product.Platform", b =>
                {
                    b.Navigation("PlatformItems");
                });
#pragma warning restore 612, 618
        }
    }
}
