<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Models\Analytics\**" />
    <Compile Remove="Models\Crawler\**" />
    <Compile Remove="Models\Member\**" />
    <Compile Remove="Views\Member\**" />
    <Content Remove="Models\Analytics\**" />
    <Content Remove="Models\Crawler\**" />
    <Content Remove="Models\Member\**" />
    <Content Remove="Views\Member\**" />
    <EmbeddedResource Remove="Models\Analytics\**" />
    <EmbeddedResource Remove="Models\Crawler\**" />
    <EmbeddedResource Remove="Models\Member\**" />
    <EmbeddedResource Remove="Views\Member\**" />
    <None Remove="Models\Analytics\**" />
    <None Remove="Models\Crawler\**" />
    <None Remove="Models\Member\**" />
    <None Remove="Views\Member\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
