<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Models\Crawler\" />
    <Folder Include="Models\Member\" />
    <Folder Include="Models\Analytics\" />
    <Folder Include="Models\Product\" />
    <Folder Include="Views\Member\" />
    <Folder Include="Views\Product\" />
    <Folder Include="Views\Search\" />
  </ItemGroup>

</Project>
